# Generated by Django 3.2 on 2023-01-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='prodcut',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
